version: "3.9"

services:
    web:
        container_name: web-mynetwork-local
        hostname: pinus-strobus
        build:
            dockerfile: ./nginx/Dockerfile
        ports:
            - 81:80
        networks:
            - default
        restart: unless-stopped
    app:
        container_name: app-mynetwork-local
        hostname: salix-nigra
        build:
            dockerfile: ./php/Dockerfile
        networks:
            - default
        restart: unless-stopped
    db:
        container_name: db-mynetwork-local
        hostname: quercus-alba
        image: mysql:latest
        volumes:
            - ./mysqldata:/var/lib/mysql
        restart: unless-stopped
        networks:
            - default
    adminer:
        container_name: adminer-mynetwork-local
        hostname: ulmus-rubra
        image: adminer
        ports:
            - 82:8080
        environment:
            ADMINER_DEFAULT_SERVER: quercus-alba
            ADMINER_DESIGN: lucas-sandery
        depends_on:
            - db
        restart: unless-stopped
        networks:
            - default
volumes:
    mysqldata:
networks:
    default:
        name: mynetwork.local
        external: false
