services:
    web:
        container_name: web
        hostname: pinus-strobus
        image: nginx:latest
        ports:
            - 81:80
        volumes:
            - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - default
        restart: unless-stopped
    app:
        container_name: app
        hostname: salix-nigra
        build:
            dockerfile: ./php/Dockerfile
        volumes:
            - ./app:/app
        networks:
            - default
        restart: unless-stopped
networks:
    default:
        name: mynetwork.local
        external: false
