services:
    web:
        container_name: web
        hostname: pinus-strobus
        image: nginx:latest
        ports:
            - 81:80
        volumes:
            - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - default
        restart: unless-stopped
    app:
        container_name: app
        hostname: salix-nigra
        build:
            dockerfile: ./php/Dockerfile
        volumes:
            - ./app:/app
        networks:
            - default
        restart: unless-stopped
    db:
        container_name: db
        hostname: quercus-alba
        image: mysql:8.0
        volumes:
            - ./mysqldata:/var/lib/mysql
        ports:
            - 3306:3306
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_USER: user
            MYSQL_PASSWORD: secret
            MYSQL_DATABASE: docker-php
volumes:
    mysqldata:
networks:
    default:
        name: mynetwork.local
        external: false
