version: "3.9"

services:
    web:
        container_name: web-mynetwork-local
        hostname: pinus-strobus
        image: nginx:latest
        ports:
            - 81:80
        volumes:
            - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - default
        restart: unless-stopped
    app:
        container_name: app-mynetwork-local
        hostname: salix-nigra
        build:
            dockerfile: ./php/Dockerfile
        volumes:
            - ./app:/app
        networks:
            - default
        restart: unless-stopped
    db:
        container_name: db-mynetwork-local
        hostname: quercus-alba
        image: mysql:8.0
        volumes:
            - ./mysqldata:/var/lib/mysql
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_USER: user
            MYSQL_PASSWORD: secret
            MYSQL_DATABASE: docker-php
        restart: unless-stopped
        networks:
            - default
    adminer:
        container_name: adminer-mynetwork-local
        hostname: ulmus-rubra
        image: adminer
        ports:
            - 82:8080
        environment:
            ADMINER_DEFAULT_SERVER: quercus-alba
            ADMINER_DESIGN: lucas-sandery
        depends_on:
            - db
        restart: unless-stopped
        networks:
            - default
volumes:
    mysqldata:
networks:
    default:
        name: mynetwork.local
        external: false
